//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V3.Client;
using CloudFoundry.CloudController.V3.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace CloudFoundry.CloudController.V3.Test.Serialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ProcessesExperimentalTest
    {

        [TestMethod]
        public void TestScalingProcessFromItsAppRequest()
        {
            string json = @"{
  ""instances"": 3,
  ""memory_in_mb"": 100,
  ""disk_in_mb"": 100
}";

            ScalingProcessFromItsAppRequest request = new ScalingProcessFromItsAppRequest();

            request.Instances = 3;
            request.MemoryInMb = 100;
            request.DiskInMb = 100;
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
        [TestMethod]
        public void TestUpdateProcessRequest()
        {
            string json = @"{
  ""command"": ""X""
}";

            UpdateProcessRequest request = new UpdateProcessRequest();

            request.Command = "X";
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
        [TestMethod]
        public void TestScalingProcessRequest()
        {
            string json = @"{
  ""instances"": 3,
  ""memory_in_mb"": 100,
  ""disk_in_mb"": 100
}";

            ScalingProcessRequest request = new ScalingProcessRequest();

            request.Instances = 3;
            request.MemoryInMb = 100;
            request.DiskInMb = 100;
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
    }
}
