//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace CloudFoundry.CloudController.V2.Test.Serialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class DomainsDeprecatedTest
    {

        [TestMethod]
        public void TestCreateDomainOwnedByGivenOrganizationDeprecatedRequest()
        {
            string json = @"{
  ""name"": ""exmaple.com"",
  ""wildcard"": true,
  ""owning_organization_guid"": ""c63b5b03-0026-4dff-9f68-ca83885c3e07""
}";

            CreateDomainOwnedByGivenOrganizationDeprecatedRequest request = new CreateDomainOwnedByGivenOrganizationDeprecatedRequest();

            request.Name = "exmaple.com";
            request.Wildcard = true;
            request.OwningOrganizationGuid = new Guid("c63b5b03-0026-4dff-9f68-ca83885c3e07");
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
        [TestMethod]
        public void TestCreateSharedDomainDeprecatedRequest()
        {
            string json = @"{
  ""name"": ""example.com"",
  ""wildcard"": true
}";

            CreateSharedDomainDeprecatedRequest request = new CreateSharedDomainDeprecatedRequest();

            request.Name = "example.com";
            request.Wildcard = true;
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
    }
}
