//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace CloudFoundry.CloudController.V2.Test.Serialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServiceInstancesTest
    {

        [TestMethod]
        public void TestBindingServiceInstanceToRouteRequest()
        {
            string json = @"{
  ""parameters"": {
    ""the_service_broker"": ""wants this object""
  }
}";

            BindingServiceInstanceToRouteRequest request = new BindingServiceInstanceToRouteRequest();

            request.Parameters = TestUtil.GetJsonDictonary(@"{""the_service_broker"":""wants this object""}");

            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
        [TestMethod]
        public void TestCreateServiceInstanceRequest()
        {
            string json = @"{
  ""space_guid"": ""bf327d94-2d1e-4f36-abc4-b830426f5bda"",
  ""name"": ""my-service-instance"",
  ""service_plan_guid"": ""bf327d94-2d1e-4f36-abc4-b830426f5bda"",
  ""parameters"": {
    ""the_service_broker"": ""wants this object""
  },
  ""tags"": [
    ""accounting"",
    ""mongodb""
  ]
}";

            CreateServiceInstanceRequest request = new CreateServiceInstanceRequest();

            request.SpaceGuid = new Guid("bf327d94-2d1e-4f36-abc4-b830426f5bda");
            request.Name = "my-service-instance";
            request.ServicePlanGuid = new Guid("bf327d94-2d1e-4f36-abc4-b830426f5bda");
            request.Parameters = TestUtil.GetJsonDictonary(@"{""the_service_broker"":""wants this object""}");

            request.Tags = Array.ConvertAll(TestUtil.GetJsonArray(@"[""accounting"",""mongodb""]"), (p => p.ToString()));

            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
        [TestMethod]
        public void TestUpdateServiceInstanceRequest()
        {
            string json = @"{""service_plan_guid"":""188d12ec-02af-4421-8009-a2745251b035"",""parameters"":{""the_service_broker"":""wants this object""}}";

            UpdateServiceInstanceRequest request = new UpdateServiceInstanceRequest();

            request.ServicePlanGuid = new Guid("188d12ec-02af-4421-8009-a2745251b035");
            request.Parameters = TestUtil.GetJsonDictonary(@"{""the_service_broker"":""wants this object""}");

            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
    }
}
