//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V3.Client;
using CloudFoundry.CloudController.V3.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom.Compiler;

namespace CloudFoundry.CloudController.V3.Test.Deserialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class AppRoutesTest
    {


        [TestMethod]
        public void TestListRoutesResponse()
        {
            string json = @"{
  ""pagination"": {
    ""total_results"": 2,
    ""first"": {
      ""href"": ""/v3/apps/guid-52ae6c97-4ba6-49a5-ae9e-24b1bebd99a7/routes?page=1=50""
    },
    ""last"": {
      ""href"": ""/v3/apps/guid-52ae6c97-4ba6-49a5-ae9e-24b1bebd99a7/routes?page=1=50""
    },
    ""next"": null,
    ""previous"": null
  },
  ""resources"": [
    {
      ""guid"": ""ac884a9e-0a29-4f63-8276-0e03d6559dfe"",
      ""host"": ""host-16"",
      ""path"": """",
      ""created_at"": ""2015-06-30T07:10:48Z"",
      ""updated_at"": null,
      ""_links"": {
        ""space"": {
          ""href"": ""/v2/spaces/585f9880-39b8-4eaa-ab1f-b8264fc344d5""
        },
        ""domain"": {
          ""href"": ""/v2/domains/d5fdcc0b-0a6e-4351-b013-50996e481920""
        }
      }
    },
    {
      ""guid"": ""ad825658-2b6e-4f4f-9778-716012c9b973"",
      ""host"": ""host-17"",
      ""path"": ""/foo/bar"",
      ""created_at"": ""2015-06-30T07:10:48Z"",
      ""updated_at"": null,
      ""_links"": {
        ""space"": {
          ""href"": ""/v2/spaces/585f9880-39b8-4eaa-ab1f-b8264fc344d5""
        },
        ""domain"": {
          ""href"": ""/v2/domains/3afae5b6-559f-47b2-ad70-e05bf858fe74""
        }
      }
    }
  ]
}";

            PagedResponseCollection<ListRoutesResponse> page = Utilities.DeserializePage<ListRoutesResponse>(json, null);

            Assert.AreEqual("ac884a9e-0a29-4f63-8276-0e03d6559dfe", TestUtil.ToTestableString(page[0].Guid), true);
            Assert.AreEqual("host-16", TestUtil.ToTestableString(page[0].Host), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].Path), true);
            Assert.AreEqual("2015-06-30T07:10:48Z", TestUtil.ToTestableString(page[0].CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].UpdatedAt), true);
            Assert.AreEqual("ad825658-2b6e-4f4f-9778-716012c9b973", TestUtil.ToTestableString(page[1].Guid), true);
            Assert.AreEqual("host-17", TestUtil.ToTestableString(page[1].Host), true);
            Assert.AreEqual("/foo/bar", TestUtil.ToTestableString(page[1].Path), true);
            Assert.AreEqual("2015-06-30T07:10:48Z", TestUtil.ToTestableString(page[1].CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[1].UpdatedAt), true);
        }
    }
}
