//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom.Compiler;

namespace CloudFoundry.CloudController.V2.Test.Deserialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class PrivateDomainsTest
    {


        [TestMethod]
        public void TestRetrievePrivateDomainResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""ca942912-a67b-4757-965a-11ec5f3e40b5"",
    ""url"": ""/v2/private_domains/50378c3d-cd75-4fad-8238-0b458107207e"",
    ""created_at"": ""2016-10-12T12:29:07Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""vcap.me"",
    ""owning_organization_guid"": ""ca942912-a67b-4757-965a-11ec5f3e40b5"",
    ""owning_organization_url"": ""/v2/organizations/3bdef454-d929-4ebe-8db8-8a54edeb7711"",
    ""shared_organizations_url"": ""/v2/private_domains/50378c3d-cd75-4fad-8238-0b458107207e/shared_organizations""
  }
}";

            RetrievePrivateDomainResponse obj = Utilities.DeserializeJson<RetrievePrivateDomainResponse>(json);

            Assert.AreEqual("ca942912-a67b-4757-965a-11ec5f3e40b5", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/private_domains/50378c3d-cd75-4fad-8238-0b458107207e", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-10-12T12:29:07Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("vcap.me", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("ca942912-a67b-4757-965a-11ec5f3e40b5", TestUtil.ToTestableString(obj.OwningOrganizationGuid), true);
            Assert.AreEqual("/v2/organizations/3bdef454-d929-4ebe-8db8-8a54edeb7711", TestUtil.ToTestableString(obj.OwningOrganizationUrl), true);
            Assert.AreEqual("/v2/private_domains/50378c3d-cd75-4fad-8238-0b458107207e/shared_organizations", TestUtil.ToTestableString(obj.SharedOrganizationsUrl), true);
        }

        [TestMethod]
        public void TestListAllPrivateDomainsResponse()
        {
            string json = @"{
  ""total_results"": 4,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""0662b6b9-9736-46ba-b51f-ca914b4e8469"",
        ""url"": ""/v2/private_domains/50378c3d-cd75-4fad-8238-0b458107207e"",
        ""created_at"": ""2016-10-12T12:29:07Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""vcap.me"",
        ""owning_organization_guid"": ""0662b6b9-9736-46ba-b51f-ca914b4e8469"",
        ""owning_organization_url"": ""/v2/organizations/3bdef454-d929-4ebe-8db8-8a54edeb7711"",
        ""shared_organizations_url"": ""/v2/private_domains/50378c3d-cd75-4fad-8238-0b458107207e/shared_organizations""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""0662b6b9-9736-46ba-b51f-ca914b4e8469"",
        ""url"": ""/v2/private_domains/353f1217-7825-4824-aafe-be91aaf9ce1b"",
        ""created_at"": ""2016-10-12T12:29:09Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""domain-10.example.com"",
        ""owning_organization_guid"": ""0662b6b9-9736-46ba-b51f-ca914b4e8469"",
        ""owning_organization_url"": ""/v2/organizations/60bc9ae2-cc31-4659-9b59-0e2ca0240a0a"",
        ""shared_organizations_url"": ""/v2/private_domains/353f1217-7825-4824-aafe-be91aaf9ce1b/shared_organizations""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""0662b6b9-9736-46ba-b51f-ca914b4e8469"",
        ""url"": ""/v2/private_domains/8effc32b-3c7f-4223-89f7-41dfbf9c0228"",
        ""created_at"": ""2016-10-12T12:29:09Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""domain-11.example.com"",
        ""owning_organization_guid"": ""0662b6b9-9736-46ba-b51f-ca914b4e8469"",
        ""owning_organization_url"": ""/v2/organizations/df083a0a-3e10-477f-a4a8-106ba44ef28f"",
        ""shared_organizations_url"": ""/v2/private_domains/8effc32b-3c7f-4223-89f7-41dfbf9c0228/shared_organizations""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""0662b6b9-9736-46ba-b51f-ca914b4e8469"",
        ""url"": ""/v2/private_domains/58bf609d-d981-491b-8912-91c275ec8d8c"",
        ""created_at"": ""2016-10-12T12:29:09Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""domain-12.example.com"",
        ""owning_organization_guid"": ""0662b6b9-9736-46ba-b51f-ca914b4e8469"",
        ""owning_organization_url"": ""/v2/organizations/081c8c2b-ec4f-489b-9cc9-250844bcbf03"",
        ""shared_organizations_url"": ""/v2/private_domains/58bf609d-d981-491b-8912-91c275ec8d8c/shared_organizations""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllPrivateDomainsResponse> page = Utilities.DeserializePage<ListAllPrivateDomainsResponse>(json, null);

            Assert.AreEqual("4", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("0662b6b9-9736-46ba-b51f-ca914b4e8469", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/private_domains/50378c3d-cd75-4fad-8238-0b458107207e", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-10-12T12:29:07Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("vcap.me", TestUtil.ToTestableString(page[0].Name), true);
            Assert.AreEqual("0662b6b9-9736-46ba-b51f-ca914b4e8469", TestUtil.ToTestableString(page[0].OwningOrganizationGuid), true);
            Assert.AreEqual("/v2/organizations/3bdef454-d929-4ebe-8db8-8a54edeb7711", TestUtil.ToTestableString(page[0].OwningOrganizationUrl), true);
            Assert.AreEqual("/v2/private_domains/50378c3d-cd75-4fad-8238-0b458107207e/shared_organizations", TestUtil.ToTestableString(page[0].SharedOrganizationsUrl), true);
            Assert.AreEqual("0662b6b9-9736-46ba-b51f-ca914b4e8469", TestUtil.ToTestableString(page[1].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/private_domains/353f1217-7825-4824-aafe-be91aaf9ce1b", TestUtil.ToTestableString(page[1].EntityMetadata.Url), true);
            Assert.AreEqual("2016-10-12T12:29:09Z", TestUtil.ToTestableString(page[1].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[1].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("domain-10.example.com", TestUtil.ToTestableString(page[1].Name), true);
            Assert.AreEqual("0662b6b9-9736-46ba-b51f-ca914b4e8469", TestUtil.ToTestableString(page[1].OwningOrganizationGuid), true);
            Assert.AreEqual("/v2/organizations/60bc9ae2-cc31-4659-9b59-0e2ca0240a0a", TestUtil.ToTestableString(page[1].OwningOrganizationUrl), true);
            Assert.AreEqual("/v2/private_domains/353f1217-7825-4824-aafe-be91aaf9ce1b/shared_organizations", TestUtil.ToTestableString(page[1].SharedOrganizationsUrl), true);
            Assert.AreEqual("0662b6b9-9736-46ba-b51f-ca914b4e8469", TestUtil.ToTestableString(page[2].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/private_domains/8effc32b-3c7f-4223-89f7-41dfbf9c0228", TestUtil.ToTestableString(page[2].EntityMetadata.Url), true);
            Assert.AreEqual("2016-10-12T12:29:09Z", TestUtil.ToTestableString(page[2].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[2].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("domain-11.example.com", TestUtil.ToTestableString(page[2].Name), true);
            Assert.AreEqual("0662b6b9-9736-46ba-b51f-ca914b4e8469", TestUtil.ToTestableString(page[2].OwningOrganizationGuid), true);
            Assert.AreEqual("/v2/organizations/df083a0a-3e10-477f-a4a8-106ba44ef28f", TestUtil.ToTestableString(page[2].OwningOrganizationUrl), true);
            Assert.AreEqual("/v2/private_domains/8effc32b-3c7f-4223-89f7-41dfbf9c0228/shared_organizations", TestUtil.ToTestableString(page[2].SharedOrganizationsUrl), true);
            Assert.AreEqual("0662b6b9-9736-46ba-b51f-ca914b4e8469", TestUtil.ToTestableString(page[3].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/private_domains/58bf609d-d981-491b-8912-91c275ec8d8c", TestUtil.ToTestableString(page[3].EntityMetadata.Url), true);
            Assert.AreEqual("2016-10-12T12:29:09Z", TestUtil.ToTestableString(page[3].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[3].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("domain-12.example.com", TestUtil.ToTestableString(page[3].Name), true);
            Assert.AreEqual("0662b6b9-9736-46ba-b51f-ca914b4e8469", TestUtil.ToTestableString(page[3].OwningOrganizationGuid), true);
            Assert.AreEqual("/v2/organizations/081c8c2b-ec4f-489b-9cc9-250844bcbf03", TestUtil.ToTestableString(page[3].OwningOrganizationUrl), true);
            Assert.AreEqual("/v2/private_domains/58bf609d-d981-491b-8912-91c275ec8d8c/shared_organizations", TestUtil.ToTestableString(page[3].SharedOrganizationsUrl), true);
        }

        [TestMethod]
        public void TestCreatePrivateDomainOwnedByGivenOrganizationResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""b4023df7-73c8-41df-a207-48e57321c086"",
    ""url"": ""/v2/private_domains/3e266a09-f30e-4ddd-bc8f-2e0f06c79d51"",
    ""created_at"": ""2016-10-12T12:29:09Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""exmaple.com"",
    ""owning_organization_guid"": ""b4023df7-73c8-41df-a207-48e57321c086"",
    ""owning_organization_url"": ""/v2/organizations/cacb810e-ac58-4804-a405-a04e442cc296"",
    ""shared_organizations_url"": ""/v2/private_domains/3e266a09-f30e-4ddd-bc8f-2e0f06c79d51/shared_organizations""
  }
}";

            CreatePrivateDomainOwnedByGivenOrganizationResponse obj = Utilities.DeserializeJson<CreatePrivateDomainOwnedByGivenOrganizationResponse>(json);

            Assert.AreEqual("b4023df7-73c8-41df-a207-48e57321c086", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/private_domains/3e266a09-f30e-4ddd-bc8f-2e0f06c79d51", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-10-12T12:29:09Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("exmaple.com", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("b4023df7-73c8-41df-a207-48e57321c086", TestUtil.ToTestableString(obj.OwningOrganizationGuid), true);
            Assert.AreEqual("/v2/organizations/cacb810e-ac58-4804-a405-a04e442cc296", TestUtil.ToTestableString(obj.OwningOrganizationUrl), true);
            Assert.AreEqual("/v2/private_domains/3e266a09-f30e-4ddd-bc8f-2e0f06c79d51/shared_organizations", TestUtil.ToTestableString(obj.SharedOrganizationsUrl), true);
        }

        [TestMethod]
        public void TestListAllSharedOrganizationsForPrivateDomainResponse()
        {
            string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""84db2009-dd79-4f34-a430-39e6d9daa1a9"",
        ""url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081"",
        ""created_at"": ""2016-10-12T12:29:09Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-89"",
        ""billing_enabled"": false,
        ""quota_definition_guid"": ""84db2009-dd79-4f34-a430-39e6d9daa1a9"",
        ""status"": ""active"",
        ""quota_definition_url"": ""/v2/quota_definitions/b5a50249-96f3-464c-a439-44768465848c"",
        ""spaces_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/spaces"",
        ""domains_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/domains"",
        ""private_domains_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/private_domains"",
        ""users_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/users"",
        ""managers_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/managers"",
        ""billing_managers_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/billing_managers"",
        ""auditors_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/auditors"",
        ""app_events_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/app_events"",
        ""space_quota_definitions_url"": ""/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/space_quota_definitions""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllSharedOrganizationsForPrivateDomainResponse> page = Utilities.DeserializePage<ListAllSharedOrganizationsForPrivateDomainResponse>(json, null);

            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("84db2009-dd79-4f34-a430-39e6d9daa1a9", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-10-12T12:29:09Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-89", TestUtil.ToTestableString(page[0].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[0].BillingEnabled), true);
            Assert.AreEqual("84db2009-dd79-4f34-a430-39e6d9daa1a9", TestUtil.ToTestableString(page[0].QuotaDefinitionGuid), true);
            Assert.AreEqual("active", TestUtil.ToTestableString(page[0].Status), true);
            Assert.AreEqual("/v2/quota_definitions/b5a50249-96f3-464c-a439-44768465848c", TestUtil.ToTestableString(page[0].QuotaDefinitionUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/spaces", TestUtil.ToTestableString(page[0].SpacesUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/domains", TestUtil.ToTestableString(page[0].DomainsUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/private_domains", TestUtil.ToTestableString(page[0].PrivateDomainsUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/users", TestUtil.ToTestableString(page[0].UsersUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/managers", TestUtil.ToTestableString(page[0].ManagersUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/billing_managers", TestUtil.ToTestableString(page[0].BillingManagersUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/auditors", TestUtil.ToTestableString(page[0].AuditorsUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/app_events", TestUtil.ToTestableString(page[0].AppEventsUrl), true);
            Assert.AreEqual("/v2/organizations/c320c186-1439-4b9d-8891-deaada8a4081/space_quota_definitions", TestUtil.ToTestableString(page[0].SpaceQuotaDefinitionsUrl), true);
        }

        [TestMethod]
        public void TestFilterPrivateDomainsByNameResponse()
        {
            string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""b343c51c-901a-4106-afad-0b609fa235ee"",
        ""url"": ""/v2/private_domains/21697b23-6a04-40bf-963b-c59dbc35b04c"",
        ""created_at"": ""2016-10-12T12:29:09Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""my-domain.com"",
        ""owning_organization_guid"": ""b343c51c-901a-4106-afad-0b609fa235ee"",
        ""owning_organization_url"": ""/v2/organizations/0291b964-6564-432f-8ebc-7a6728917c1b"",
        ""shared_organizations_url"": ""/v2/private_domains/21697b23-6a04-40bf-963b-c59dbc35b04c/shared_organizations""
      }
    }
  ]
}";

            PagedResponseCollection<FilterPrivateDomainsByNameResponse> page = Utilities.DeserializePage<FilterPrivateDomainsByNameResponse>(json, null);

            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("b343c51c-901a-4106-afad-0b609fa235ee", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/private_domains/21697b23-6a04-40bf-963b-c59dbc35b04c", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-10-12T12:29:09Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("my-domain.com", TestUtil.ToTestableString(page[0].Name), true);
            Assert.AreEqual("b343c51c-901a-4106-afad-0b609fa235ee", TestUtil.ToTestableString(page[0].OwningOrganizationGuid), true);
            Assert.AreEqual("/v2/organizations/0291b964-6564-432f-8ebc-7a6728917c1b", TestUtil.ToTestableString(page[0].OwningOrganizationUrl), true);
            Assert.AreEqual("/v2/private_domains/21697b23-6a04-40bf-963b-c59dbc35b04c/shared_organizations", TestUtil.ToTestableString(page[0].SharedOrganizationsUrl), true);
        }
    }
}
