//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom.Compiler;

namespace CloudFoundry.CloudController.V2.Test.Deserialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ResourceMatchTest
    {


        [TestMethod]
        public void TestListAllMatchingResourcesResponse()
        {
            string json = @"[
  {
    ""sha1"": ""11eb4376edc1b1aa0440d9abcb6dfea44905bd03"",
    ""size"": 36
  }
]";

            ListAllMatchingResourcesResponse[] obj = Utilities.DeserializeJsonArray<ListAllMatchingResourcesResponse>(json);

            Assert.AreEqual("11eb4376edc1b1aa0440d9abcb6dfea44905bd03", TestUtil.ToTestableString(obj[0].Sha1), true);
            Assert.AreEqual("36", TestUtil.ToTestableString(obj[0].Size), true);
        }
    }
}
