//------------------------------------------------------------------------------
// <auto-generated>
  //     This code was generated by a tool.
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  // </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.QualityTools.Testing.Fakes;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.CodeDom.Compiler;
using System.Net;
using System.Threading.Tasks;

namespace CloudFoundry.CloudController.V2.Client.Test.Fake
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServiceKeysEndpoint
{
        [TestMethod]
        public void ListAllServiceKeysTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""613624c1-fc10-4220-a737-71f41cf07268"",
        ""url"": ""/v2/service_keys/e343411f-1785-4a1a-9ab4-57dc3e5280d8"",
        ""created_at"": ""2016-10-12T12:29:08Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-43"",
        ""service_instance_guid"": ""613624c1-fc10-4220-a737-71f41cf07268"",
        ""credentials"": {
          ""creds-key-2"": ""creds-val-2""
        },
        ""service_instance_url"": ""/v2/service_instances/a23600d1-0354-4e22-afb6-f6abc9b94b32""
      }
    }
  ]
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();


                var obj = cfClient.ServiceKeys.ListAllServiceKeys().Result;

                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalResults), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalPages), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.PreviousUrl), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.NextUrl), true);
                Assert.AreEqual("613624c1-fc10-4220-a737-71f41cf07268", TestUtil.ToTestableString(obj[0].EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_keys/e343411f-1785-4a1a-9ab4-57dc3e5280d8", TestUtil.ToTestableString(obj[0].EntityMetadata.Url), true);
                Assert.AreEqual("2016-10-12T12:29:08Z", TestUtil.ToTestableString(obj[0].EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-43", TestUtil.ToTestableString(obj[0].Name), true);
                Assert.AreEqual("613624c1-fc10-4220-a737-71f41cf07268", TestUtil.ToTestableString(obj[0].ServiceInstanceGuid), true);
                Assert.AreEqual("/v2/service_instances/a23600d1-0354-4e22-afb6-f6abc9b94b32", TestUtil.ToTestableString(obj[0].ServiceInstanceUrl), true);

            }
        }

        [TestMethod]
        public void RetrieveServiceKeyTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""7eaf784f-8fca-4e72-84dc-16e3e77bdd11"",
    ""url"": ""/v2/service_keys/31583eb6-a611-41d4-98e1-946c1b43fc1c"",
    ""created_at"": ""2016-10-12T12:29:09Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""name-82"",
    ""service_instance_guid"": ""7eaf784f-8fca-4e72-84dc-16e3e77bdd11"",
    ""credentials"": {
      ""creds-key-11"": ""creds-val-11""
    },
    ""service_instance_url"": ""/v2/service_instances/20ecb468-1524-4e86-87d9-13c90a20258a""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                var obj = cfClient.ServiceKeys.RetrieveServiceKey(guid).Result;


                Assert.AreEqual("7eaf784f-8fca-4e72-84dc-16e3e77bdd11", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_keys/31583eb6-a611-41d4-98e1-946c1b43fc1c", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-10-12T12:29:09Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-82", TestUtil.ToTestableString(obj.Name), true);
                Assert.AreEqual("7eaf784f-8fca-4e72-84dc-16e3e77bdd11", TestUtil.ToTestableString(obj.ServiceInstanceGuid), true);
                Assert.AreEqual("/v2/service_instances/20ecb468-1524-4e86-87d9-13c90a20258a", TestUtil.ToTestableString(obj.ServiceInstanceUrl), true);

            }
        }

        [TestMethod]
        public void CreateServiceKeyTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""d528fd61-43b6-476c-bad7-0d586e81b8ea"",
    ""url"": ""/v2/service_keys/06ff6cbd-bf17-4322-8110-9eb9c62c4093"",
    ""created_at"": ""2016-10-12T12:29:08Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""name-56"",
    ""service_instance_guid"": ""d528fd61-43b6-476c-bad7-0d586e81b8ea"",
    ""credentials"": {
      ""creds-key-4"": ""creds-val-4""
    },
    ""service_instance_url"": ""/v2/service_instances/a645d9e6-718e-4140-899a-eb4962e39e23""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)201;
                var cfClient = clients.CreateCloudFoundryClient();

                CreateServiceKeyRequest value = new CreateServiceKeyRequest();


                var obj = cfClient.ServiceKeys.CreateServiceKey(value).Result;


                Assert.AreEqual("d528fd61-43b6-476c-bad7-0d586e81b8ea", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_keys/06ff6cbd-bf17-4322-8110-9eb9c62c4093", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-10-12T12:29:08Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-56", TestUtil.ToTestableString(obj.Name), true);
                Assert.AreEqual("d528fd61-43b6-476c-bad7-0d586e81b8ea", TestUtil.ToTestableString(obj.ServiceInstanceGuid), true);
                Assert.AreEqual("/v2/service_instances/a645d9e6-718e-4140-899a-eb4962e39e23", TestUtil.ToTestableString(obj.ServiceInstanceUrl), true);

            }
        }

        [TestMethod]
        public void DeleteServiceKeyTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                clients.ExpectedStatusCode = (HttpStatusCode)204;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                cfClient.ServiceKeys.DeleteServiceKey(guid).Wait();

            }
        }

    }
}