//------------------------------------------------------------------------------
// <auto-generated>
  //     This code was generated by a tool.
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  // </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.QualityTools.Testing.Fakes;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.CodeDom.Compiler;
using System.Net;
using System.Threading.Tasks;

namespace CloudFoundry.CloudController.V2.Client.Test.Fake
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class AppUsageEventsEndpoint
{
        [TestMethod]
        public void RetrieveAppUsageEventTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""e724d32b-89ce-4c1e-a915-f08e8f4f9c19"",
    ""url"": ""/v2/app_usage_events/fb357c1a-a86c-4722-97e1-8e4ca4a1187f"",
    ""created_at"": ""2016-05-26T11:34:45Z""
  },
  ""entity"": {
    ""state"": ""STARTED"",
    ""previous_state"": null,
    ""memory_in_mb_per_instance"": 564,
    ""previous_memory_in_mb_per_instance"": null,
    ""instance_count"": 1,
    ""previous_instance_count"": null,
    ""app_guid"": ""e724d32b-89ce-4c1e-a915-f08e8f4f9c19"",
    ""app_name"": ""name-2227"",
    ""space_guid"": ""e724d32b-89ce-4c1e-a915-f08e8f4f9c19"",
    ""space_name"": ""name-2228"",
    ""org_guid"": ""e724d32b-89ce-4c1e-a915-f08e8f4f9c19"",
    ""buildpack_guid"": ""e724d32b-89ce-4c1e-a915-f08e8f4f9c19"",
    ""buildpack_name"": ""name-2229"",
    ""package_state"": ""STAGED"",
    ""previous_package_state"": null,
    ""parent_app_guid"": null,
    ""parent_app_name"": null,
    ""process_type"": ""web"",
    ""task_name"": null,
    ""task_guid"": null
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                var obj = cfClient.AppUsageEvents.RetrieveAppUsageEvent(guid).Result;


                Assert.AreEqual("e724d32b-89ce-4c1e-a915-f08e8f4f9c19", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/app_usage_events/fb357c1a-a86c-4722-97e1-8e4ca4a1187f", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-05-26T11:34:45Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("STARTED", TestUtil.ToTestableString(obj.State), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.PreviousState), true);
                Assert.AreEqual("564", TestUtil.ToTestableString(obj.MemoryInMbPerInstance), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.PreviousMemoryInMbPerInstance), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj.InstanceCount), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.PreviousInstanceCount), true);
                Assert.AreEqual("e724d32b-89ce-4c1e-a915-f08e8f4f9c19", TestUtil.ToTestableString(obj.AppGuid), true);
                Assert.AreEqual("name-2227", TestUtil.ToTestableString(obj.AppName), true);
                Assert.AreEqual("e724d32b-89ce-4c1e-a915-f08e8f4f9c19", TestUtil.ToTestableString(obj.SpaceGuid), true);
                Assert.AreEqual("name-2228", TestUtil.ToTestableString(obj.SpaceName), true);
                Assert.AreEqual("e724d32b-89ce-4c1e-a915-f08e8f4f9c19", TestUtil.ToTestableString(obj.OrgGuid), true);
                Assert.AreEqual("e724d32b-89ce-4c1e-a915-f08e8f4f9c19", TestUtil.ToTestableString(obj.BuildpackGuid), true);
                Assert.AreEqual("name-2229", TestUtil.ToTestableString(obj.BuildpackName), true);
                Assert.AreEqual("STAGED", TestUtil.ToTestableString(obj.PackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.PreviousPackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.ParentAppGuid), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.ParentAppName), true);
                Assert.AreEqual("web", TestUtil.ToTestableString(obj.ProcessType), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.TaskName), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.TaskGuid), true);

            }
        }

        [TestMethod]
        public void PurgeAndReseedAppUsageEventsTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                clients.ExpectedStatusCode = (HttpStatusCode)204;
                var cfClient = clients.CreateCloudFoundryClient();


                cfClient.AppUsageEvents.PurgeAndReseedAppUsageEvents().Wait();

            }
        }

        [TestMethod]
        public void ListAllAppUsageEventsTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""total_results"": 2,
  ""total_pages"": 2,
  ""prev_url"": null,
  ""next_url"": ""/v2/app_usage_events?after_guid=40d6fa2d-9169-48cc-86e3-3280d98836d7=asc=2=1"",
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""bb787b48-5adb-4e03-834c-36472d90f862"",
        ""url"": ""/v2/app_usage_events/d898422c-15e8-49b2-8089-171553b5c2e7"",
        ""created_at"": ""2016-05-26T11:34:45Z""
      },
      ""entity"": {
        ""state"": ""STARTED"",
        ""previous_state"": null,
        ""memory_in_mb_per_instance"": 564,
        ""previous_memory_in_mb_per_instance"": null,
        ""instance_count"": 1,
        ""previous_instance_count"": null,
        ""app_guid"": ""bb787b48-5adb-4e03-834c-36472d90f862"",
        ""app_name"": ""name-2221"",
        ""space_guid"": ""bb787b48-5adb-4e03-834c-36472d90f862"",
        ""space_name"": ""name-2222"",
        ""org_guid"": ""bb787b48-5adb-4e03-834c-36472d90f862"",
        ""buildpack_guid"": ""bb787b48-5adb-4e03-834c-36472d90f862"",
        ""buildpack_name"": ""name-2223"",
        ""package_state"": ""STAGED"",
        ""previous_package_state"": null,
        ""parent_app_guid"": null,
        ""parent_app_name"": null,
        ""process_type"": ""web"",
        ""task_name"": null,
        ""task_guid"": null
      }
    }
  ]
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();


                var obj = cfClient.AppUsageEvents.ListAllAppUsageEvents().Result;

                Assert.AreEqual("2", TestUtil.ToTestableString(obj.Properties.TotalResults), true);
                Assert.AreEqual("2", TestUtil.ToTestableString(obj.Properties.TotalPages), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.PreviousUrl), true);
                Assert.AreEqual("/v2/app_usage_events?after_guid=40d6fa2d-9169-48cc-86e3-3280d98836d7=asc=2=1", TestUtil.ToTestableString(obj.Properties.NextUrl), true);
                Assert.AreEqual("bb787b48-5adb-4e03-834c-36472d90f862", TestUtil.ToTestableString(obj[0].EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/app_usage_events/d898422c-15e8-49b2-8089-171553b5c2e7", TestUtil.ToTestableString(obj[0].EntityMetadata.Url), true);
                Assert.AreEqual("2016-05-26T11:34:45Z", TestUtil.ToTestableString(obj[0].EntityMetadata.CreatedAt), true);
                Assert.AreEqual("STARTED", TestUtil.ToTestableString(obj[0].State), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].PreviousState), true);
                Assert.AreEqual("564", TestUtil.ToTestableString(obj[0].MemoryInMbPerInstance), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].PreviousMemoryInMbPerInstance), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj[0].InstanceCount), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].PreviousInstanceCount), true);
                Assert.AreEqual("bb787b48-5adb-4e03-834c-36472d90f862", TestUtil.ToTestableString(obj[0].AppGuid), true);
                Assert.AreEqual("name-2221", TestUtil.ToTestableString(obj[0].AppName), true);
                Assert.AreEqual("bb787b48-5adb-4e03-834c-36472d90f862", TestUtil.ToTestableString(obj[0].SpaceGuid), true);
                Assert.AreEqual("name-2222", TestUtil.ToTestableString(obj[0].SpaceName), true);
                Assert.AreEqual("bb787b48-5adb-4e03-834c-36472d90f862", TestUtil.ToTestableString(obj[0].OrgGuid), true);
                Assert.AreEqual("bb787b48-5adb-4e03-834c-36472d90f862", TestUtil.ToTestableString(obj[0].BuildpackGuid), true);
                Assert.AreEqual("name-2223", TestUtil.ToTestableString(obj[0].BuildpackName), true);
                Assert.AreEqual("STAGED", TestUtil.ToTestableString(obj[0].PackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].PreviousPackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].ParentAppGuid), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].ParentAppName), true);
                Assert.AreEqual("web", TestUtil.ToTestableString(obj[0].ProcessType), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].TaskName), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].TaskGuid), true);

            }
        }

    }
}